openapi: 3.0.1
info:
  title: Batch Control
  description: Monolithic API developed in Java Spring Boot.
  version: 1.0.0
tags:
- name: "Stores"
  description: "Store Methods"
- name: "Products"
  description: "Product Methods"
- name: "Batches"
  description: "Batch Methods"

externalDocs:
  description: Read more about BatchControl
  url: https://github.com/yhonathanpavan/Compass.UOL-Projeto-BicoOn#readme
servers:
- url: http://localhost:8080/v1
paths:

  /stores:
    post:
      tags:
      - "Stores"
      summary: Register a store by ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StoreCreateForm"
      responses:
        201: 
          description: "CREATED"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensBadRequest"
  /stores/{id}:
    parameters: 
    - name: id
      in: path 
      schema:
        type: integer
      required: true 
    get:
      tags:
      - "Stores"
      summary: Details a store by ID
      responses:
        200:
          description: "OK"
          content: 
            application/json:
              schema:
                  $ref: "#/components/schemas/Store"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensNotFound"
    put:
      tags:
      - "Stores"
      summary: Update a store by ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Store"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Store"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensBadRequest"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensNotFound"
                  
  /stores/{id}/products:
    parameters: 
        - name: id
          in: path 
          schema:
            type: integer
          required: true 
    get:
      tags:
      - "Products"
      summary: Lists all products in a store
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ProductPageable"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensNotFound"
    post:
      tags:
      - "Products"
      summary: Register a product by ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCreateForm"
      responses:
        201: 
          description: "CREATED"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensBadRequest"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensNotFound"
  /stores/{id}/products/{productId}:
    parameters: 
    - name: id
      in: path 
      schema:
        type: integer
      required: true 
    - name: productId
      in: path 
      schema:
        type: integer
      required: true 
    get:
      tags:
      - "Products"
      summary: Details a product by ID
      responses:
        200:
          description: "OK"
          content: 
            application/json:
              schema:
                  $ref: "#/components/schemas/Product"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensNotFound"
    put:
      tags:
      - "Products"
      summary: Update a product by ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductUpdateForm"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductUpdateForm"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensBadRequest"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensNotFound"
                
  /products/{id}/batches:
    parameters: 
    - name: id
      in: path 
      schema:
        type: integer
      required: true 
    get:
      tags:
      - "Batches"
      summary: Lists all batches of a product
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Batch"
    post:
      tags:
      - "Batches"
      summary: Register a batch of a product
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BatchCreateForm"
      responses:
        201: 
          description: "CREATED"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensBadRequest"
  /products/{id}/batches/retail:
    parameters: 
    - name: id
      in: path 
      schema:
        type: integer
      required: true 
    put:
      tags:
      - "Batches"
      summary: Update amount of a batch for Retail
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BatchFormPutFromRetailDto"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchLeavingDto"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensBadRequest"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnprocessableEntity"
  /products/{id}/batches/wholesale:
    parameters: 
      - name: id
        in: path 
        schema:
          type: integer
        required: true 
    put:
      tags:
      - "Batches"
      summary: Update amount of a batch for Wholesale
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BatchFormPutFromWholesaleDto"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchLeavingDto"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MensagensBadRequest"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnprocessableEntity"
           
components:
  schemas:
    Store:
      type: object
      properties: 
        companyName:
          type: string
        phoneNumber: 
          type: string
        cnpj:
          type: string
        city:
          type: string
        active:
          type: boolean
          
    StoreCreateForm:
      type: object
      properties: 
        companyName:
          type: string
        phoneNumber: 
          type: string
        cnpj:
          type: string
        city:
          type: string
          
    Product:
      type: object
      properties: 
        id: 
          type: integer
        name:
          type: string
        description: 
          type: string
        active:
          type: boolean
        storeId:
          type: integer
          
    ProductPageable:
      type: object
      properties: 
        content:
          type: array
          items:
            type: object
            properties: 
              name:
                type: string
              description: 
                type: string
              active:
                type: boolean
        pageable:
          type: string
        totalElements:
          type: integer
        totalPages:
          type: integer
        last:
          type: boolean
        size:
          type: integer
        number:
          type: integer
        sort:
          type: object
          properties: 
            empty: 
              type: boolean
            unsorted:
              type: boolean
            sorted:
              type: boolean
        numberOfElements:
          type: integer
        first: 
          type: boolean
        empty:
          type: boolean
          
    ProductCreateForm:
      type: object
      properties: 
        name:
          type: string
        description: 
          type: string
          
    ProductUpdateForm:
      type: object
      properties: 
        name:
          type: string
        description: 
          type: string
        active:
          type: boolean
          
    Batch:
      type: object
      properties: 
        id: 
          type: string
        description:
          type: string
        expirationDate: 
          type: string
        amount:
          type: integer
          
    BatchCreateForm:
      type: object
      properties: 
        id: 
          type: string
        description:
          type: string
        expirationDate: 
          type: string
        amount:
          type: integer
          
    BatchLeavingDto:
      type: object
      properties: 
        productName: 
          type: string
        idBatch:
          type: string
          
    BatchFormPutFromRetailDto:
      type: object
      properties: 
        amount:
          type: integer
          
    BatchFormPutFromWholesaleDto:
      type: object
      properties: 
        numberBatches:
          type: integer
        productsPerBatch:
          type: integer
          
    MensagensBadRequest:
      properties:
        timestamp:   
          type: integer
        status:   
          type: integer
        error:
          type: string
        path:
          type: string
    
    MensagensNotFound:
       properties:
        timestamp:   
          type: integer
        status:   
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string
          
    UnprocessableEntity:
       properties:
        timestamp:   
          type: integer
        status:   
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string


